title: Olivia Knoedt
description: >-
  Olivia is a software engineer from London, UK. She's currently at 101 Ways as a Lead Tech Consultant.
domain: livkndt.github.io
url: https://livkndt.github.io
baseurl: ""
markdown: kramdown
cdn_url: https://d19w7e3j8gkywb.cloudfront.net/
paginate: 9
paginate_path: "/blog/page:num/"
timezone: Europe/London

github_username:  livkndt
linkedin_username: oliviaknoedt
instagram_username: livkndt_dev
google_analytics: G-RMJY3EWX4E
medium_username: oliviaknoedt

show_excerpts: true
site_credits: >-
  This website was built using Jekyll & is evolved from their Minima theme. 💜

disqus:
  shortname: livkndt

collections:
  positions:
    output: true

defaults:
  - scope:
      path: ""
      type: "positions"
    values:
      layout: "position"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

safe: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-loading-lazy
sass:
  style: compressed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - readme_img/
   - development/
